### ISSUE TITLE
Yes! An Alexa fix for MyQ that works!

### ISSUE THREAD

**Issue by ShakeyPlace** [spenwall/myq-alexa#1]
Hi, was able to set up and working in minutes after spending days on others that were either way over my head or didn't work. Alexa commands working perfectly for opening and closing door. I even added several custom commands. I also added some confirmation prompts for now.
My problem is whenever I request status I get returned with the "something went wrong" statement. :(  
Is there something I need to do with the package-lock json? Or perhaps I need to define the status codes?

**Comment by spenwall** [comment]
Yes. I didn't noticed the status problem before as I don't use it very often. I will work on it today and let you know when it is fixed. Thanks for reporting this, and I am glad it is working otherwise.

**Comment by spenwall** [comment]
I have updated the index.js file to include the door statuses. You should be able to just copy the code into your alex code editor. Be sure to update the username and password sections and you should be good to go.
