### ISSUE TITLE
Is this library functional?

### ISSUE THREAD

**Issue by billatq** [spenwall/myq-alexa#2]
Would you happen to have tested this recently?

I ran into these problems when I tried to run it:
- The myq-api package doesn't seem to produce usable artifacts. It runs into an issue where you aren't able to load the dist/myq file. Unclear if babel isn't doing its thing properly, or whatnot, but there's no dist folder in the artifacts.
- The scoped myq-api package can't be found because the requires has myq-api instead of @spenwall/myq-api. If you fix this, you run into the dist folder issue.
- If you fix all these things up, you find that the response from the myq api doesn't seem to work, and you end up with "Error handled: Cannot read property 'id' of undefined"

**Comment by spenwall** [comment]
I hadn't publish the correct package with @spenwall/myq-api. I have fixed this now.
