### ISSUE TITLE
Door is Undefined Error Again

### ISSUE THREAD

**Issue by jincollingo** [spenwall/myq-alexa#5]
Getting the response that the door is undefined again.
this is from my logs:
2021-01-08T20:21:09.183Z 736452fa-a313-4be9-84d2- INFO { MyQError: Unidentified error returned from service. at Function.handleServiceError (/va

**Comment by spenwall** [comment]
Thanks for reporting. I see that MyQ updated their api and am hoping that the myq-api package that I use will update soon. If not I will fork and get this working again soon.

**Comment by spenwall** [comment]
If you would like to use my fork of myq-api you can update the following lines in the code. The only change is that I changed the constant for the myq-api version from 5.1 to 5 and that seemed for fix the problem.

index.js
from `const MyQ = require("myq-api");` to `const MyQ = require("@spenwall/myq-api");`

package.json
from `"myq-api": "^2.0"` to `"@spenwall/myq-api": "^2.0"`

**Comment by jincollingo** [comment]
Thank you spenwall.  I used your fork and its working again.  I thought I read the API version is up to 6 now so not sure how long this will last.

Thanks,
Jerry
